// Code generated by "stringer -type gameStatus"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WaitingForPlayers-0]
	_ = x[InProgress-1]
	_ = x[Over-2]
}

const _gameStatus_name = "WaitingForPlayersInProgressOver"

var _gameStatus_index = [...]uint8{0, 17, 27, 31}

func (i gameStatus) String() string {
	if i < 0 || i >= gameStatus(len(_gameStatus_index)-1) {
		return "gameStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _gameStatus_name[_gameStatus_index[i]:_gameStatus_index[i+1]]
}
