// Code generated by "stringer -type ChallengeDifficulty -trimprefix Challenge"; DO NOT EDIT.

package words

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChallengeEasy-0]
	_ = x[ChallengeMedium-1]
	_ = x[ChallengeHard-2]
}

const _ChallengeDifficulty_name = "EasyMediumHard"

var _ChallengeDifficulty_index = [...]uint8{0, 4, 10, 14}

func (i ChallengeDifficulty) String() string {
	if i < 0 || i >= ChallengeDifficulty(len(_ChallengeDifficulty_index)-1) {
		return "ChallengeDifficulty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChallengeDifficulty_name[_ChallengeDifficulty_index[i]:_ChallengeDifficulty_index[i+1]]
}
